name: Update BBC Trends

on:
    schedule:
        - cron: '15,45 * * * *' # 每小時第 15 和 45 分鐘執行
    workflow_dispatch:

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Force install Chromium for Puppeteer
              run: npx puppeteer browsers install chrome

            - name: Run Puppeteer Scraper
              run: pnpm run scrape:bbc

            - name: Commit and Push Results
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  git config --global user.name "Gary Lin"
                  git config --global user.email "garylin0969@gmail.com"

                  # 先保存爬蟲的新資料
                  cp data/bbc-trends.json /tmp/bbc-trends.json

                  # 拉取最新的程式碼
                  git pull origin main

                  # 把新爬到的資料覆蓋回去
                  cp /tmp/bbc-trends.json data/bbc-trends.json

                  # 提交並推送
                  git add data/bbc-trends.json
                  git commit -m "update bbc trends [CI] $(TZ=Asia/Taipei date '+%Y-%m-%d %H:%M:%S')" || echo "Nothing to commit"
                  git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
